import sys
import re

CDR3_REGEX = '(TT[TC]|TA[CT])(TT[CT]|TA[TC]|CA[TC]|GT[AGCT]|TGG)(TG[TC])(([GA][AGCT])|TC)[AGCT]([ACGT]{3}){5,32}TGGG[GCT][GCT]'
MIN_DIST_FROM_START = 100

id = None
seq = None
for line in sys.stdin:
    line = line.rstrip()
    if not id:
        id = line
    else:
        seq = line
        m = re.search(CDR3_REGEX, seq);
        if m:
            index = seq.index(m.group(0))
            if index >= 100:
                print id + '\n' + seq + '\n'
                
        id = None
        seq = None
        


#line  = 'AGCACTGCCTCCATACAACTCAGCAGCCTAACATCTGATGACTCTGCGGTCTATTACTGTGCAAGAGTCTACTATGATTACCCCTGGTTTGCTTACTGGGGCCAAGGGACTCTGGTCACTGTCTCTGCAGAGCCTGCAAGAGAGCCCACCATCTACCCACTGACATTCCCACAAGCTCTGTCAAGTGACCCAGTGATAATCGGCTGCCTGATTCATGATTACTTCCCTTCCGGCACGATGAATGTGACCTGGGGAAAGAGTGGGAAGGATATAACCACCGTAAACTTCCCACCTGCCCTGGCCTCTGGGGGACGGTACACCATGAGCAGCCAGTTGACCCTGCCAGCTGTCGAGTGCCCAGAAGGAGAATCCGTGAAATGTTCCGTGCAACATGACTCTAACCCCGTCCAAGAATTGAACGTGAATTGCCCTGGTATCTGTTCTCCTCCTACTACTCCTCCTCCACCTTCCTGCCAGCCCAGCCTGTCACTGCAGCGGCC'
#line2 = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
#m = re.search('(TT[TC]|TA[CT])(TT[CT]|TA[TC]|CA[TC]|GT[AGCT]|TGG)(TG[TC])(([GA][AGCT])|TC)[AGCT]([ACGT]{3}){5,32}TGGG[GCT][GCT]', line)

#print m

#if m:
#    print m.group(0)
    
#    print line.index(m.group(0))